---
- name: "consul | consul_deploy | Main"
  block:
    - name: "consul | consul_deploy | Deploy Consul Control Plane"
      ansible.builtin.import_tasks:
        file: consul_control_plane.yml
      when:
        - "'consul_servers' in group_names"
      tags:
        - consul_servers

    - name: "consul | consul_deploy | Deploy Consul Agents"
      ansible.builtin.import_tasks:
        file: consul_agents.yml
      when:
        - "'consul_agents' in group_names"
        - "'consul_servers' not in group_names"
      tags:
        - consul_agents
