---
- name: "Set reload-check & restart-check variable"
  ansible.builtin.set_fact:
    _consul_service_need_daemon_reload: false
    _consul_service_need_reload: false
    _consul_service_need_restart: false

- name: "Import merge_variables.yml"
  ansible.builtin.include_tasks: merge_variables.yml

- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install_envoy.yml"
  ansible.builtin.include_tasks: install_envoy.yml
  when: consul_envoy_install

- name: "Import install.yml"
  ansible.builtin.include_tasks: "install.yml"

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml

- name: "Populate service facts"
  ansible.builtin.service_facts:

- name: "Set restart-check variable"
  ansible.builtin.set_fact:
    _consul_service_need_restart: true
  when: ansible_facts.services[consul_service_name~'.service'].state != 'running'

- name: "Enable service: {{ consul_service_name }}"
  ansible.builtin.service:
    name: "{{ consul_service_name }}"
    enabled: true

- name: "Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: true
  when: _consul_service_need_daemon_reload

- name: "Start service: {{ consul_service_name }}"
  ansible.builtin.service:
    name: "{{ consul_service_name }}"
    state: restarted
  throttle: 1
  when:
    - consul_start_service
    - _consul_service_need_restart

- name: "Reload service: {{ consul_service_name }}"
  ansible.builtin.service:
    name: "{{ consul_service_name }}"
    state: reloaded
  throttle: 1
  when:
    - consul_start_service
    - _consul_service_need_reload
    - not _consul_service_need_restart
