---
- name: "merge_variables | Merge stringified configuration"
  vars:
    _config_to_merge: "{{ consul_configuration_string }}"
  ansible.builtin.set_fact:
    consul_configuration: "{{
      consul_configuration |
      combine(_config_to_merge | from_yaml, recursive=true)
      }}"

- name: "merge_variables | Merge server specific stringified configuration"
  vars:
    _config_to_merge: "{{ consul_server_configuration_string }}"
  ansible.builtin.set_fact:
    consul_configuration: "{{
      consul_configuration |
      combine(_config_to_merge | from_yaml, recursive=true)
      }}"
  when:
    - consul_enable_server

- name: "merge_variables | Merge join configuration"
  vars:
    _config_to_merge: "{{ consul_join_configuration }}"
  ansible.builtin.set_fact:
    consul_configuration: "{{
      consul_configuration |
      combine(_config_to_merge, recursive=true)
      }}"

- name: "merge_variables | Merge addresses configuration"
  vars:
    _config_to_merge: "{{ consul_address_configuration }}"
  ansible.builtin.set_fact:
    consul_configuration: "{{
      consul_configuration |
      combine(_config_to_merge, recursive=true)
      }}"

- name: "merge_variables | Merge TLS configuration"
  when: consul_enable_tls
  block:
    - name: "merge_variables | Merge TLS configuration"
      vars:
        _config_to_merge:
          tls: "{{ consul_tls_configuration }}"
      ansible.builtin.set_fact:
        consul_configuration: "{{
          consul_configuration |
          combine(_config_to_merge, recursive=true)
          }}"

    - name: "merge_variables | Add certificates directory to extra_files_dir"
      ansible.builtin.set_fact:
        consul_extra_files_list: "{{
          consul_extra_files_list +
          consul_certificates_extra_files_dir
          | unique
          | sort
          }}"

- name: "merge_variables | Merge extra configuration settings"
  vars:
    _config_to_merge: "{{ consul_extra_configuration }}"
  ansible.builtin.set_fact:
    consul_configuration: "{{
      consul_configuration |
      combine(_config_to_merge, recursive=true)
      }}"

- name: "merge_variables | Merge log to file configuration"
  vars:
    _config_to_merge: "{{ consul_log_to_file_configuration }}"
  ansible.builtin.set_fact:
    consul_configuration: "{{
      consul_configuration |
      combine(_config_to_merge, recursive=true)
      }}"
  when: consul_enable_log_to_file

- name: "merge_variables | Merge telemetry configuration"
  block:
    - name: "merge_variables | Merge prometheus metrics configuration"
      vars:
        _config_to_merge:
          prometheus_retention_time: "{{ consul_prometheus_retention_time }}"
      ansible.builtin.set_fact:
        consul_telemetry_configuration: "{{
          consul_telemetry_configuration |
          combine(_config_to_merge, recursive=true)
          }}"
      when: consul_enable_prometheus_metrics

    - name: "merge_variables | Merge telemtry configuration"
      vars:
        _config_to_merge:
          telemetry: "{{ consul_telemetry_configuration }}"
      ansible.builtin.set_fact:
        consul_configuration: "{{
          consul_configuration |
          combine(_config_to_merge, recursive=true)
          }}"
