---
- name: "recursive_copy_extra_dirs | Ensure destination directory exists"
  ansible.builtin.file:
    path: "{{ dir_source_item.dest }}"
    state: directory
    mode: "0755"

- name: "recursive_copy_extra_dirs | Create extra directory sources"
  ansible.builtin.file:
    path: "{{ dir_source_item.dest }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "{{ dir_source_item.src }}/"
  when: item.state == 'directory'

- name: "recursive_copy_extra_dirs | Template extra directory sources"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ dir_source_item.dest }}/{{ item.path | regex_replace('\\.j2$', '') }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0700"
  with_community.general.filetree: "{{ dir_source_item.src }}/"
  when: item.state == 'file'
