---
- name: "vault | vault_deploy | Main"
  block:
    - name: "vault | vault_deploy | Deploy Vault Control Plane"
      ansible.builtin.import_tasks:
        file: vault_control_plane.yml
      when:
        - "'vault_servers' in group_names"
      tags:
        - vault_servers
