---
- name: "prerequisites | Create group {{ vault_group }}"
  ansible.builtin.group:
    name: "{{ vault_group }}"
    state: present

- name: "prerequisites | Create user {{ vault_user }}"
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    shell: /bin/false
    state: present

- name: "prerequisites | Create directory {{ vault_config_dir }}"
  ansible.builtin.file:
    path: "{{ vault_config_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"

- name: "prerequisites | Create directory {{ vault_data_dir}}"
  ansible.builtin.file:
    path: "{{ vault_data_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"

- name: "prerequisites | Create directory {{ vault_certs_dir }}"
  ansible.builtin.file:
    path: "{{ vault_certs_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"

- name: "prerequisites | Create directory {{ vault_logs_dir }}"
  ansible.builtin.file:
    path: "{{ vault_logs_dir }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"
  when: vault_enable_log_to_file
