---
- name: "cleanup_backups | Check if root CA backup directory exists"
  ansible.builtin.stat:
    path: "{{ hashistack_ca_root_backup_dir }}"
  register: _hashistack_ca_root_backup_dir_stat
  delegate_to: localhost

- name: "cleanup_backups | Check if intermediate CA backup directory exists"
  ansible.builtin.stat:
    path: "{{ hashistack_ca_intermediate_backup_dir }}"
  register: _hashistack_ca_intermediate_backup_dir_stat
  delegate_to: localhost

- name: "cleanup_backups | Root CA backups"
  when:
    - _hashistack_ca_root_backup_dir_stat.stat.exists
    - _hashistack_ca_root_backup_dir_stat.stat.isdir
  delegate_to: localhost
  block:
    - name: "cleanup_backups | Find root CA backup certificates"
      ansible.builtin.find:
        paths: "{{ hashistack_ca_root_backup_dir }}"
        patterns: "*.crt"
      register: _hashistack_ca_root_backup_files

    - name: "cleanup_backups | Check expiration for root CA backup certificates"
      when: _hashistack_ca_root_backup_files.matched > 0
      community.crypto.x509_certificate_info:
        path: "{{ item.path }}"
      register: _hashistack_ca_root_cert_info
      loop: "{{ _hashistack_ca_root_backup_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      failed_when: false
      ignore_errors: true

    - name: "cleanup_backups | Remove expired root CA backup certificates"
      when: item.item.expired | default(false)
      ansible.builtin.file:
        path: "{{ item.item.path }}"
        state: absent
      loop: "{{ _hashistack_ca_root_cert_info.results }}"

- name: "cleanup_backups | Intermediate CA backups"
  when:
    - _hashistack_ca_intermediate_backup_dir_stat.stat.exists
    - _hashistack_ca_intermediate_backup_dir_stat.stat.isdir
  delegate_to: localhost
  block:
    - name: "cleanup_backups | Find intermediate CA backup certificates"
      ansible.builtin.find:
        paths: "{{ hashistack_ca_intermediate_backup_dir }}"
        patterns: "*.crt"
      register: _hashistack_ca_intermediate_backup_files

    - name: "cleanup_backups | Check expiration for intermediate CA backup certificates"
      when: _hashistack_ca_intermediate_backup_files.matched > 0
      community.crypto.x509_certificate_info:
        path: "{{ item.path }}"
      register: _hashistack_ca_intermediate_cert_info
      loop: "{{ _hashistack_ca_intermediate_backup_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      failed_when: false
      ignore_errors: true

    - name: "cleanup_backups | Remove expired intermediate CA backup certificates"
      when: item.item.expired | default(false)
      ansible.builtin.file:
        path: "{{ item.item.path }}"
        state: absent
      loop: "{{ _hashistack_ca_intermediate_cert_info.results }}"
