---
- name: "load_group_vars | Stat group specific config file"
  ansible.builtin.stat:
    path: "{{ hashistack_configuration_directory }}/{{ group_name }}/{{ hashistack_configuration_global_vars_file }}"
  register: _hashistack_group_config_file
  loop: "{{ group_names }}"
  loop_control:
    loop_var: group_name
  delegate_to: localhost

- name: "load_group_vars | Load group specific variables"
  ansible.builtin.include_vars:
    dir: "{{ hashistack_configuration_directory }}/{{ item.group_name }}"
    files_matching: "{{ hashistack_configuration_global_vars_file }}"
    depth: 1
  loop: "{{ _hashistack_group_config_file.results }}"
  when: item.stat.exists
    and item.group_name in group_names
  loop_control:
    loop_var: item
  delegate_to: localhost
